variavel = input('Digite algo: ')
print('O tipo de variavel primitiva é do tipo:', type(variavel))
print('Só tem espaços?', variavel.isspace())
print('É um número?', variavel.isnumeric())
print('É alfabético?', variavel.isalpha())
print('É alfanumérico?', variavel.isalnum())
print('Foi digitado em maiúsculo?', variavel.isupper())
print('Foi digitado em minúsculo?', variavel.islower())
print('Está capitalizada?', variavel.istitle())
